import { StudentResult } from "../types/studentTypes";
import { generateSubjects } from "./helpers";

export const mockStudents: StudentResult[] = [
  {
    id: 1,
    name: "John Okoro",
    class: "Grade 1",
    age: 10,
    subjects: [
      {
        subject: "Mathematics",
        caScore: 32,
        examScore: 45,
        overall: 77,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "English",
        caScore: 28,
        examScore: 40,
        overall: 68,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Biology",
        caScore: 20,
        examScore: 25,
        overall: 45,
        passMark: 50,
        status: "Fail",
      },
      {
        subject: "Chemistry",
        caScore: 35,
        examScore: 50,
        overall: 85,
        passMark: 50,
        status: "Pass",
      },

      {
        subject: "Geography",
        caScore: 18,
        examScore: 28,
        overall: 46,
        passMark: 50,
        status: "Fail",
      },
      {
        subject: "Literature",
        caScore: 29,
        examScore: 38,
        overall: 67,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Computer",
        caScore: 34,
        examScore: 55,
        overall: 89,
        passMark: 50,
        status: "Pass",
      },
    ],
  },
  {
    id: 2,
    name: "Mary Ade",
    class: "Grade 5",
    age: 10,
    subjects: [],
  },
  {
    id: 3,
    name: "David Musa",
    class: "Grade 3",
    age: 9,
    subjects: generateSubjects(),
  },
  {
    id: 4,
    name: "Aisha Bello",
    class: "Grade 2",
    age: 8,
    subjects: generateSubjects(),
  },
  {
    id: 5,
    name: "Samuel Eze",
    class: "Grade 4",
    age: 11,
    subjects: generateSubjects(),
  },
  {
    id: 6,
    name: "Fatima Lawal",
    class: "Grade 1",
    age: 7,
    subjects: generateSubjects(),
  },
  {
    id: 7,
    name: "Ibrahim Yusuf",
    class: "Grade 5",
    age: 12,
    subjects: generateSubjects(),
  },
  {
    id: 8,
    name: "Grace Nwosu",
    class: "Grade 3",
    age: 9,
    subjects: generateSubjects(),
  },
  {
    id: 9,
    name: "Daniel Ojo",
    class: "Grade 2",
    age: 8,
    subjects: generateSubjects(),
  },
  {
    id: 10,
    name: "Zainab Ali",
    class: "Grade 4",
    age: 11,
    subjects: generateSubjects(),
  },
];
