import { StudentResult } from "../types/studentTypes";

export const mockStudents: StudentResult[] = [
  {
    id: 1,
    name: "John Okoro",
    class: "Grade 1",
    age: 10,
    subjects: [
      {
        subject: "Mathematics",
        caScore: 32,
        examScore: 45,
        overall: 77,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "English",
        caScore: 28,
        examScore: 40,
        overall: 68,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Biology",
        caScore: 20,
        examScore: 25,
        overall: 45,
        passMark: 50,
        status: "Fail",
      },
      {
        subject: "Chemistry",
        caScore: 35,
        examScore: 50,
        overall: 85,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Physics",
        caScore: 22,
        examScore: 30,
        overall: 52,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Economics",
        caScore: 30,
        examScore: 42,
        overall: 72,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Government",
        caScore: 25,
        examScore: 35,
        overall: 60,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Geography",
        caScore: 18,
        examScore: 28,
        overall: 46,
        passMark: 50,
        status: "Fail",
      },
      {
        subject: "Literature",
        caScore: 29,
        examScore: 38,
        overall: 67,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Computer",
        caScore: 34,
        examScore: 55,
        overall: 89,
        passMark: 50,
        status: "Pass",
      },
    ],
  },
  {
    id: 2,
    name: "Mary Ade",
    age: 10,
    class: "Grade 5",
    subjects: [
      {
        subject: "Mathematics",
        caScore: 30,
        examScore: 40,
        overall: 70,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "English",
        caScore: 35,
        examScore: 50,
        overall: 85,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Biology",
        caScore: 25,
        examScore: 35,
        overall: 60,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Chemistry",
        caScore: 20,
        examScore: 25,
        overall: 45,
        passMark: 50,
        status: "Fail",
      },
      {
        subject: "Physics",
        caScore: 28,
        examScore: 32,
        overall: 60,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Economics",
        caScore: 22,
        examScore: 30,
        overall: 52,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Government",
        caScore: 18,
        examScore: 26,
        overall: 44,
        passMark: 50,
        status: "Fail",
      },
      {
        subject: "Geography",
        caScore: 27,
        examScore: 39,
        overall: 66,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Literature",
        caScore: 31,
        examScore: 41,
        overall: 72,
        passMark: 50,
        status: "Pass",
      },
      {
        subject: "Computer",
        caScore: 36,
        examScore: 48,
        overall: 84,
        passMark: 50,
        status: "Pass",
      },
    ],
  },
];
